"""
Report Generator — Quantum Security Intelligence Platform
=========================================================
Generates enterprise-grade PDF and Excel (.xlsx) reports from scan data.

Public API
----------
    generate_pdf_report(data: dict)   -> bytes
    generate_excel_report(data: dict) -> bytes

Modular Structure
-----------------
    _build_pdf_header()
    _build_executive_narrative()
    _build_summary_section()
    _build_compliance_snapshot()
    _build_findings_table()
    _build_node_analysis_table()
    _build_pdf_footer()

Team CypherRed261 | PSB Hackathon 2026
"""

import io
import datetime
from typing import Any

# ── ReportLab Imports ──────────────────────────────────────────
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether
)
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate

# ── openpyxl Imports ───────────────────────────────────────────
from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter


# ──────────────────────────────────────────────────────────────
# BRAND CONSTANTS
# ──────────────────────────────────────────────────────────────

BRAND_RED       = colors.HexColor("#C41230")
BRAND_GOLD      = colors.HexColor("#F5A623")
BRAND_DARK      = colors.HexColor("#0D0D0F")
BRAND_SURFACE   = colors.HexColor("#F8F6F3")
BRAND_BORDER    = colors.HexColor("#E5E3E0")
BRAND_TEXT_MUTED = colors.HexColor("#555566")
BRAND_SUCCESS   = colors.HexColor("#22C55E")
BRAND_WARNING   = colors.HexColor("#F59E0B")
BRAND_DANGER    = colors.HexColor("#EF4444")
BRAND_CRITICAL  = colors.HexColor("#7C2D12")
BRAND_INFO      = colors.HexColor("#3B82F6")

SEVERITY_COLORS = {
    "CRITICAL": colors.HexColor("#7C2D12"),
    "HIGH":     colors.HexColor("#C41230"),
    "MEDIUM":   colors.HexColor("#F59E0B"),
    "LOW":      colors.HexColor("#22C55E"),
}
SEVERITY_BG = {
    "CRITICAL": colors.HexColor("#FEF2F2"),
    "HIGH":     colors.HexColor("#FFF0F0"),
    "MEDIUM":   colors.HexColor("#FFFBEB"),
    "LOW":      colors.HexColor("#F0FDF4"),
}

FOOTER_TEXT = (
    "Generated by Quantum Security Intelligence Engine  ·  "
    "Team CypherRed261  ·  PSB Hackathon 2026"
)


# ──────────────────────────────────────────────────────────────
# SORTING HELPER
# ──────────────────────────────────────────────────────────────

_SEV_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
_TYPE_ORDER = {"MISCONFIG": 0, "RECOMMENDATION": 1}


def _sort_findings(findings: list) -> list:
    """Sort findings: CRITICAL→HIGH→MEDIUM→LOW, then MISCONFIG before RECOMMENDATION."""
    def sort_key(f):
        sev = (f.get("severity") or "LOW").upper()
        ftype = (f.get("type") or "RECOMMENDATION").upper()
        return (_SEV_ORDER.get(sev, 9), _TYPE_ORDER.get(ftype, 9))
    return sorted(findings, key=sort_key)


# ──────────────────────────────────────────────────────────────
# STYLE REGISTRY
# ──────────────────────────────────────────────────────────────

def _build_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="ReportTitle",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=colors.white,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="ReportSubTitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#FFD0A0"),
        spaceAfter=2,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="SectionHeading",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=BRAND_DARK,
        spaceBefore=14,
        spaceAfter=6,
        fontName="Helvetica-Bold",
        borderPadding=(0, 0, 4, 0),
    ))
    styles.add(ParagraphStyle(
        name="Narrative",
        parent=styles["Normal"],
        fontSize=9.5,
        textColor=colors.HexColor("#333344"),
        leading=15,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="FooterText",
        parent=styles["Normal"],
        fontSize=7.5,
        textColor=colors.HexColor("#7F8090"),
        alignment=TA_CENTER,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="TableHeader",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.white,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="TableCell",
        parent=styles["Normal"],
        fontSize=8,
        textColor=BRAND_DARK,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="TableCellMono",
        parent=styles["Normal"],
        fontSize=7.5,
        textColor=colors.HexColor("#333344"),
        fontName="Courier",
    ))
    styles.add(ParagraphStyle(
        name="ComplianceLabel",
        parent=styles["Normal"],
        fontSize=8.5,
        textColor=BRAND_TEXT_MUTED,
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="ComplianceValue",
        parent=styles["Normal"],
        fontSize=8.5,
        textColor=BRAND_DARK,
        fontName="Helvetica",
    ))
    return styles


# ──────────────────────────────────────────────────────────────
# PDF: HEADER BANNER
# ──────────────────────────────────────────────────────────────

def _build_pdf_header(data: dict, styles) -> list:
    """Branded header banner — product name, scan version, domain, timestamp."""
    domain      = data.get("domain", "unknown")
    version     = data.get("scan_version", "v1.0")
    scan_id     = data.get("scan_id", "N/A")
    generated_at = data.get("generated_at", datetime.datetime.utcnow().isoformat())
    generated_by = data.get("generated_by", "Quantum Security Engine")

    # Banner table — full width dark background
    header_data = [
        [
            Paragraph("🔐 Quantum-Proof Systems Scanner", styles["ReportTitle"]),
            Paragraph(
                f"<b>Scan Report</b> · {version}",
                ParagraphStyle("hdr_right", parent=styles["ReportSubTitle"], alignment=TA_RIGHT)
            ),
        ],
        [
            Paragraph(f"Domain: <b>{domain}</b>", styles["ReportSubTitle"]),
            Paragraph(
                f"Generated: {generated_at[:19].replace('T', ' ')} UTC",
                ParagraphStyle("hdr_right2", parent=styles["ReportSubTitle"], alignment=TA_RIGHT)
            ),
        ],
        [
            Paragraph(f"Scan ID: {scan_id}", styles["ReportSubTitle"]),
            Paragraph(
                f"By: {generated_by}",
                ParagraphStyle("hdr_right3", parent=styles["ReportSubTitle"], alignment=TA_RIGHT)
            ),
        ],
    ]

    t = Table(header_data, colWidths=["60%", "40%"])
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, -1), BRAND_DARK),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [BRAND_DARK, BRAND_DARK, BRAND_DARK]),
        ("TOPPADDING",  (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("LINEBELOW",   (0, 2), (-1, 2), 2, BRAND_GOLD),
    ]))

    return [t, Spacer(1, 10)]


# ──────────────────────────────────────────────────────────────
# PDF: EXECUTIVE NARRATIVE
# ──────────────────────────────────────────────────────────────

def _build_executive_narrative(data: dict, styles) -> list:
    profile   = data.get("risk_profile", {})
    risk      = (profile.get("risk_level") or "UNKNOWN").upper()
    pqc_score = profile.get("pqc_score", 0)
    hndl      = profile.get("hndl_risk", False)
    domain    = data.get("domain", "this asset")

    # Compose narrative based on risk level
    if risk in ("CRITICAL", "HIGH"):
        narrative = (
            f"<b>Executive Summary:</b> The scan of <b>{domain}</b> reveals a "
            f"<font color='#C41230'><b>{risk}</b></font> quantum vulnerability posture "
            f"with a PQC Compliance Score of <b>{pqc_score}/100</b>. "
            "This domain relies on classical cryptographic primitives (RSA/ECC) that are "
            "computationally broken by Shor's algorithm on sufficiently powerful quantum computers. "
        )
        if hndl:
            narrative += (
                "A <b>Harvest-Now-Decrypt-Later (HNDL)</b> risk is active — adversaries may already "
                "be capturing encrypted traffic for future quantum decryption. "
            )
        narrative += (
            "Immediate PQC migration planning in accordance with NIST FIPS 203/204/205 is recommended. "
            "Prioritise key exchange migration to CRYSTALS-Kyber (ML-KEM) and signatures to "
            "CRYSTALS-Dilithium (ML-DSA) or SLH-DSA."
        )
    elif risk == "MEDIUM":
        narrative = (
            f"<b>Executive Summary:</b> The scan of <b>{domain}</b> indicates a "
            f"<font color='#F59E0B'><b>MEDIUM</b></font> quantum risk level "
            f"with a PQC Compliance Score of <b>{pqc_score}/100</b>. "
            "While classical cipher hygiene is satisfactory (TLS 1.3 detected), "
            "no post-quantum key encapsulation mechanisms (KEMs) or signature algorithms "
            "are present. A hybrid PQC migration roadmap should be initiated within 12 months "
            "to achieve NIST PQC alignment ahead of the cryptographically relevant quantum computer (CRQC) "
            "timeline (est. 2030–2035)."
        )
    else:
        narrative = (
            f"<b>Executive Summary:</b> The scan of <b>{domain}</b> returns a "
            f"<font color='#22C55E'><b>LOW</b></font> quantum risk posture "
            f"with a PQC Compliance Score of <b>{pqc_score}/100</b>. "
            "Post-quantum cryptographic primitives are detected or strong hybrid TLS configurations are in place. "
            "Continued monitoring against evolving NIST standards and RBI/CERT-IN mandates is advised."
        )

    box_data = [[Paragraph(narrative, styles["Narrative"])]]
    t = Table(box_data, colWidths=["100%"])
    t.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), BRAND_SURFACE),
        ("LEFTPADDING",  (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING",   (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 10),
        ("BOX",          (0, 0), (-1, -1), 1, BRAND_BORDER),
        ("LINERIGHT",    (0, 0), (0, -1),  3, BRAND_RED),
    ]))
    return [
        Paragraph("Executive Narrative", styles["SectionHeading"]),
        HRFlowable(width="100%", thickness=1, color=BRAND_BORDER, spaceAfter=4),
        t,
        Spacer(1, 10),
    ]


# ──────────────────────────────────────────────────────────────
# PDF: SUMMARY SECTION
# ──────────────────────────────────────────────────────────────

def _build_summary_section(data: dict, styles) -> list:
    profile = data.get("risk_profile", {})

    def val(key, fallback="N/A"):
        v = profile.get(key)
        return str(v) if v is not None else fallback

    risk         = val("risk_level")
    pqc_score    = val("pqc_score")
    agility      = val("crypto_agility_score")
    horizon      = val("quantum_risk_horizon")
    hndl         = "YES ⚠" if profile.get("hndl_risk") else "NO"
    confidence   = val("confidence_score")
    crypto_mode  = val("crypto_mode")

    row_data = [
        [Paragraph("<b>Metric</b>", styles["TableHeader"]),
         Paragraph("<b>Value</b>", styles["TableHeader"]),
         Paragraph("<b>Metric</b>", styles["TableHeader"]),
         Paragraph("<b>Value</b>", styles["TableHeader"])],
        [Paragraph("Overall Risk Level", styles["TableCell"]),
         Paragraph(f"<b>{risk}</b>", ParagraphStyle("rv", parent=styles["TableCell"],
                   textColor=SEVERITY_COLORS.get(risk, BRAND_DARK), fontName="Helvetica-Bold")),
         Paragraph("PQC Compliance Score", styles["TableCell"]),
         Paragraph(f"<b>{pqc_score} / 100</b>", styles["TableCell"])],
        [Paragraph("Crypto Agility Score", styles["TableCell"]),
         Paragraph(f"<b>{agility} / 100</b>", styles["TableCell"]),
         Paragraph("Cryptographic Mode", styles["TableCell"]),
         Paragraph(crypto_mode, styles["TableCellMono"])],
        [Paragraph("Quantum Risk Horizon", styles["TableCell"]),
         Paragraph(f"<b>{horizon} yr</b>" if horizon != "N/A" else "N/A", styles["TableCell"]),
         Paragraph("HNDL Risk", styles["TableCell"]),
         Paragraph(f"<b>{hndl}</b>", ParagraphStyle("hndl", parent=styles["TableCell"],
                   textColor=BRAND_DANGER if profile.get("hndl_risk") else BRAND_SUCCESS,
                   fontName="Helvetica-Bold"))],
        [Paragraph("Engine Confidence", styles["TableCell"]),
         Paragraph(f"<b>{confidence}%</b>", styles["TableCell"]),
         Paragraph("Scan ID", styles["TableCell"]),
         Paragraph(str(data.get("scan_id", "N/A")), styles["TableCellMono"])],
    ]

    col_w = ["30%", "20%", "30%", "20%"]
    t = Table(row_data, colWidths=col_w)
    row_colors = [BRAND_DARK] + [
        colors.HexColor("#FAFAFA") if i % 2 == 0 else colors.white
        for i in range(len(row_data) - 1)
    ]
    t.setStyle(TableStyle([
        ("ROWBACKGROUNDS",  (0, 0), (-1, -1), [BRAND_DARK] + [
            (colors.HexColor("#F4F4F6") if i % 2 else colors.white)
            for i in range(len(row_data) - 1)
        ]),
        ("TEXTCOLOR",       (0, 0), (-1, 0), colors.white),
        ("FONTNAME",        (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",        (0, 0), (-1, -1), 8.5),
        ("ALIGN",           (0, 0), (-1, -1), "LEFT"),
        ("VALIGN",          (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",      (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",   (0, 0), (-1, -1), 6),
        ("LEFTPADDING",     (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",    (0, 0), (-1, -1), 10),
        ("BOX",             (0, 0), (-1, -1), 1, BRAND_BORDER),
        ("INNERGRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E3E0")),
    ]))

    return [
        Paragraph("Risk Summary", styles["SectionHeading"]),
        HRFlowable(width="100%", thickness=1, color=BRAND_BORDER, spaceAfter=4),
        t,
        Spacer(1, 8),
    ]


# ──────────────────────────────────────────────────────────────
# PDF: COMPLIANCE SNAPSHOT
# ──────────────────────────────────────────────────────────────

def _build_compliance_snapshot(data: dict, styles) -> list:
    profile  = data.get("risk_profile", {})
    risk     = (profile.get("risk_level") or "HIGH").upper()
    pqc_score = profile.get("pqc_score", 0)

    # Derive compliance status from score + risk
    nist_status  = "Partial — Migration Recommended" if pqc_score < 50 else \
                   ("Non-Compliant — Critical Action Required" if pqc_score < 20 else "Aligned")
    rbi_status   = "Non-Compliant" if risk in ("CRITICAL", "HIGH") else \
                   ("Partial Compliance" if risk == "MEDIUM" else "Compliant")
    cert_status  = rbi_status  # CERT-IN mirrors RBI posture for this scan

    row_data = [
        [Paragraph("<b>Standard</b>", styles["TableHeader"]),
         Paragraph("<b>Alignment Status</b>", styles["TableHeader"]),
         Paragraph("<b>Notes</b>", styles["TableHeader"])],
        [Paragraph("NIST FIPS 203 (ML-KEM)", styles["TableCell"]),
         Paragraph(nist_status, styles["TableCell"]),
         Paragraph("Post-Quantum Key Encapsulation — Kyber", styles["TableCell"])],
        [Paragraph("NIST FIPS 204 (ML-DSA)", styles["TableCell"]),
         Paragraph(nist_status, styles["TableCell"]),
         Paragraph("Post-Quantum Digital Signatures — Dilithium", styles["TableCell"])],
        [Paragraph("NIST FIPS 205 (SLH-DSA)", styles["TableCell"]),
         Paragraph(nist_status, styles["TableCell"]),
         Paragraph("Stateless Hash-Based Signatures — SPHINCS+", styles["TableCell"])],
        [Paragraph("RBI Cyber Security Framework", styles["TableCell"]),
         Paragraph(rbi_status, styles["TableCell"]),
         Paragraph("Placeholder · Full RBI-CSF check pending integration", styles["TableCell"])],
        [Paragraph("CERT-IN IT Act Alignment", styles["TableCell"]),
         Paragraph(cert_status, styles["TableCell"]),
         Paragraph("Placeholder · Full CERT-IN check pending integration", styles["TableCell"])],
    ]

    t = Table(row_data, colWidths=["28%", "28%", "44%"])
    t.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [BRAND_DARK] + [
            (colors.HexColor("#F4F4F6") if i % 2 else colors.white)
            for i in range(len(row_data) - 1)
        ]),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTSIZE",      (0, 0), (-1, -1), 8),
        ("ALIGN",         (0, 0), (-1, -1), "LEFT"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("BOX",           (0, 0), (-1, -1), 1, BRAND_BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E3E0")),
    ]))

    return [
        Spacer(1, 6),
        Paragraph("Compliance Snapshot", styles["SectionHeading"]),
        HRFlowable(width="100%", thickness=1, color=BRAND_BORDER, spaceAfter=4),
        t,
        Spacer(1, 8),
    ]


# ──────────────────────────────────────────────────────────────
# PDF: FINDINGS TABLE
# ──────────────────────────────────────────────────────────────

def _build_findings_table(data: dict, styles) -> list:
    findings = _sort_findings(data.get("findings", []))

    if not findings:
        return [
            Paragraph("Findings & Recommendations", styles["SectionHeading"]),
            HRFlowable(width="100%", thickness=1, color=BRAND_BORDER, spaceAfter=4),
            Paragraph("No findings recorded for this scan.", styles["Narrative"]),
            Spacer(1, 8),
        ]

    rows = [
        [Paragraph("<b>Severity</b>", styles["TableHeader"]),
         Paragraph("<b>Type</b>", styles["TableHeader"]),
         Paragraph("<b>Title</b>", styles["TableHeader"]),
         Paragraph("<b>Description</b>", styles["TableHeader"])],
    ]

    for f in findings:
        sev   = (f.get("severity") or "LOW").upper()
        ftype = (f.get("type") or "RECOMMENDATION").upper()
        title = f.get("title") or "Security Notice"
        desc  = f.get("description") or ""

        sev_style = ParagraphStyle(
            f"sev_{sev}",
            parent=styles["TableCell"],
            textColor=SEVERITY_COLORS.get(sev, BRAND_TEXT_MUTED),
            fontName="Helvetica-Bold",
        )
        rows.append([
            Paragraph(sev, sev_style),
            Paragraph(ftype.replace("_", " "), styles["TableCell"]),
            Paragraph(title, ParagraphStyle("tf", parent=styles["TableCell"], fontName="Helvetica-Bold")),
            Paragraph(desc[:240] + ("…" if len(desc) > 240 else ""), styles["TableCell"]),
        ])

    # Alternating rows
    row_bgs = [BRAND_DARK]
    for i, f in enumerate(findings):
        sev = (f.get("severity") or "LOW").upper()
        row_bgs.append(
            SEVERITY_BG.get(sev, colors.white) if i % 2 == 0 else colors.white
        )

    t = Table(rows, colWidths=["12%", "16%", "24%", "48%"])
    t.setStyle(TableStyle([
        ("ROWBACKGROUNDS",  (0, 0), (-1, -1), row_bgs),
        ("TEXTCOLOR",       (0, 0), (-1, 0),  colors.white),
        ("FONTSIZE",        (0, 0), (-1, -1),  8),
        ("ALIGN",           (0, 0), (-1, -1),  "LEFT"),
        ("VALIGN",          (0, 0), (-1, -1),  "TOP"),
        ("TOPPADDING",      (0, 0), (-1, -1),  5),
        ("BOTTOMPADDING",   (0, 0), (-1, -1),  5),
        ("LEFTPADDING",     (0, 0), (-1, -1),  8),
        ("RIGHTPADDING",    (0, 0), (-1, -1),  8),
        ("BOX",             (0, 0), (-1, -1),  1, BRAND_BORDER),
        ("INNERGRID",       (0, 0), (-1, -1),  0.4, colors.HexColor("#E5E3E0")),
    ]))

    return [
        PageBreak(),
        Paragraph("Findings & Recommendations", styles["SectionHeading"]),
        HRFlowable(width="100%", thickness=1, color=BRAND_BORDER, spaceAfter=4),
        t,
        Spacer(1, 10),
    ]


# ──────────────────────────────────────────────────────────────
# PDF: NODE ANALYSIS TABLE
# ──────────────────────────────────────────────────────────────

def _build_node_analysis_table(data: dict, styles) -> list:
    nodes = data.get("ip_details", [])

    if not nodes:
        return [
            Paragraph("Node Analysis", styles["SectionHeading"]),
            HRFlowable(width="100%", thickness=1, color=BRAND_BORDER, spaceAfter=4),
            Paragraph("No endpoint nodes were discovered or analyzed.", styles["Narrative"]),
            Spacer(1, 8),
        ]

    rows = [
        [Paragraph("<b>IP Address</b>", styles["TableHeader"]),
         Paragraph("<b>TLS Version</b>", styles["TableHeader"]),
         Paragraph("<b>Cipher Suite</b>", styles["TableHeader"]),
         Paragraph("<b>Key Type</b>", styles["TableHeader"]),
         Paragraph("<b>Status</b>", styles["TableHeader"]),
         Paragraph("<b>Cert Status</b>", styles["TableHeader"])],
    ]

    for i, node in enumerate(nodes):
        tls  = node.get("tls") or {}
        cert = node.get("certificate") or {}
        ok   = node.get("is_successful", True)
        ip   = node.get("ip_address", "unknown")

        status_style = ParagraphStyle(
            f"s_{i}",
            parent=styles["TableCell"],
            textColor=BRAND_SUCCESS if ok else BRAND_DANGER,
            fontName="Helvetica-Bold",
        )
        cert_chain = cert.get("chain_status", "UNKNOWN")
        cert_style = ParagraphStyle(
            f"c_{i}",
            parent=styles["TableCell"],
            textColor=BRAND_SUCCESS if cert_chain == "VALID" else BRAND_DANGER,
        )

        row_bg = colors.HexColor("#F4F4F6") if i % 2 == 0 else colors.white
        rows.append([
            Paragraph(ip, styles["TableCellMono"]),
            Paragraph(tls.get("version") or "—", styles["TableCellMono"]),
            Paragraph(tls.get("cipher_suite") or "—", styles["TableCellMono"]),
            Paragraph(tls.get("public_key_type") or "—", styles["TableCell"]),
            Paragraph("SUCCESS" if ok else "FAILED", status_style),
            Paragraph(cert_chain, cert_style),
        ])

    row_bgs = [BRAND_DARK] + [
        (colors.HexColor("#F4F4F6") if i % 2 == 0 else colors.white)
        for i in range(len(nodes))
    ]

    t = Table(rows, colWidths=["16%", "12%", "28%", "16%", "12%", "16%"])
    t.setStyle(TableStyle([
        ("ROWBACKGROUNDS",  (0, 0), (-1, -1), row_bgs),
        ("TEXTCOLOR",       (0, 0), (-1, 0),  colors.white),
        ("FONTSIZE",        (0, 0), (-1, -1),  7.5),
        ("ALIGN",           (0, 0), (-1, -1),  "LEFT"),
        ("VALIGN",          (0, 0), (-1, -1),  "MIDDLE"),
        ("TOPPADDING",      (0, 0), (-1, -1),  5),
        ("BOTTOMPADDING",   (0, 0), (-1, -1),  5),
        ("LEFTPADDING",     (0, 0), (-1, -1),  8),
        ("RIGHTPADDING",    (0, 0), (-1, -1),  8),
        ("BOX",             (0, 0), (-1, -1),  1, BRAND_BORDER),
        ("INNERGRID",       (0, 0), (-1, -1),  0.4, colors.HexColor("#E5E3E0")),
    ]))

    return [
        Spacer(1, 6),
        Paragraph("Node Analysis", styles["SectionHeading"]),
        HRFlowable(width="100%", thickness=1, color=BRAND_BORDER, spaceAfter=4),
        t,
        Spacer(1, 10),
    ]


# ──────────────────────────────────────────────────────────────
# PDF: FOOTER (drawn on every page)
# ──────────────────────────────────────────────────────────────

def _build_page_footer(canvas, doc, styles):
    """Draw persistent footer on every PDF page."""
    canvas.saveState()
    w, h = A4
    # Separator line
    canvas.setStrokeColor(BRAND_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 18 * mm, w - 18 * mm, 18 * mm)
    # Footer text
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#7F8090"))
    canvas.drawCentredString(w / 2, 12 * mm, FOOTER_TEXT)
    # Page number
    canvas.drawRightString(w - 18 * mm, 12 * mm, f"Page {doc.page}")
    # Confidential label
    canvas.drawString(18 * mm, 12 * mm, "CONFIDENTIAL")
    canvas.restoreState()


# ──────────────────────────────────────────────────────────────
# PUBLIC: PDF REPORT
# ──────────────────────────────────────────────────────────────

def generate_pdf_report(data: dict) -> bytes:
    """
    Build and return a full enterprise-grade PDF report as bytes.

    Args:
        data: Unified scan dict returned by db.get_scan_for_report()

    Returns:
        bytes: Raw PDF content
    """
    buffer  = io.BytesIO()
    styles  = _build_styles()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=22 * mm,
        title=f"QPS Scan Report — {data.get('domain', 'unknown')}",
        author="Quantum Security Intelligence Engine",
        subject="Post-Quantum Cryptography Compliance Scan Report",
        creator="Team CypherRed261 | PSB Hackathon 2026",
    )

    story = []
    story += _build_pdf_header(data, styles)
    story += _build_executive_narrative(data, styles)
    story += _build_summary_section(data, styles)
    story += _build_compliance_snapshot(data, styles)
    story += _build_findings_table(data, styles)
    story += _build_node_analysis_table(data, styles)

    # Build with per-page footer callback
    doc.build(
        story,
        onFirstPage=lambda c, d: _build_page_footer(c, d, styles),
        onLaterPages=lambda c, d: _build_page_footer(c, d, styles),
    )

    buffer.seek(0)
    return buffer.read()


# ──────────────────────────────────────────────────────────────
# EXCEL HELPERS
# ──────────────────────────────────────────────────────────────

_XL_RED    = "C41230"
_XL_DARK   = "0D0D0F"
_XL_GOLD   = "F5A623"
_XL_LIGHT  = "F4F4F6"
_XL_WHITE  = "FFFFFF"
_XL_GREEN  = "22C55E"
_XL_ORANGE = "F59E0B"
_XL_DRED   = "EF4444"
_XL_CRIT   = "7C2D12"

_SEV_FILL = {
    "CRITICAL": PatternFill("solid", fgColor="FEF2F2"),
    "HIGH":     PatternFill("solid", fgColor="FFF0F0"),
    "MEDIUM":   PatternFill("solid", fgColor="FFFBEB"),
    "LOW":      PatternFill("solid", fgColor="F0FDF4"),
}
_SEV_FONT_COLOR = {
    "CRITICAL": _XL_CRIT,
    "HIGH":     _XL_RED,
    "MEDIUM":   _XL_GOLD,
    "LOW":      _XL_GREEN,
}

def _xl_header_style(color: str = _XL_DARK) -> tuple:
    """Return (Font, PatternFill, Alignment) for header row."""
    return (
        Font(bold=True, color=_XL_WHITE, size=9),
        PatternFill("solid", fgColor=color),
        Alignment(horizontal="center", vertical="center", wrap_text=True),
    )

def _xl_set_headers(ws, headers: list[str], col_widths: list[int]) -> None:
    """Write styled header row and freeze it."""
    font, fill, align = _xl_header_style()
    for col_idx, (header, width) in enumerate(zip(headers, col_widths), start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = font
        cell.fill = fill
        cell.alignment = align
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    ws.freeze_panes = "A2"

def _xl_thin_border() -> Border:
    s = Side(style="thin", color="E5E3E0")
    return Border(left=s, right=s, top=s, bottom=s)

def _xl_write_row(ws, row_idx: int, values: list, fill=None, bold=False) -> None:
    border = _xl_thin_border()
    for col_idx, val in enumerate(values, start=1):
        cell = ws.cell(row=row_idx, column=col_idx, value=str(val) if val is not None else "")
        cell.border = border
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        cell.font = Font(bold=bold, size=8.5)
        if fill:
            cell.fill = fill


# ──────────────────────────────────────────────────────────────
# PUBLIC: EXCEL REPORT
# ──────────────────────────────────────────────────────────────

def generate_excel_report(data: dict) -> bytes:
    """
    Build and return a multi-sheet Excel (.xlsx) report as bytes.

    Sheets:
        1. Summary            — Risk profile + scan metadata
        2. IP Node Details    — Per-IP TLS/Cert analysis  
        3. Findings           — All misconfigurations + recommendations
        4. Recommendations    — Filtered recommendations only

    Args:
        data: Unified scan dict returned by db.get_scan_for_report()

    Returns:
        bytes: Raw .xlsx content
    """
    wb = Workbook()

    # ── Sheet 1: Summary ──────────────────────────────────────
    ws1 = wb.active
    ws1.title = "Summary"

    profile  = data.get("risk_profile", {})
    domain   = data.get("domain", "N/A")
    scan_id  = data.get("scan_id", "N/A")
    version  = data.get("scan_version", "v1.0")
    gen_at   = data.get("generated_at", datetime.datetime.utcnow().isoformat())
    gen_by   = data.get("generated_by", "Quantum Security Engine")

    # Title banner
    ws1["A1"] = "Quantum-Proof Systems Scanner — Scan Report"
    ws1["A1"].font = Font(bold=True, size=14, color=_XL_WHITE)
    ws1["A1"].fill = PatternFill("solid", fgColor=_XL_DARK)
    ws1.merge_cells("A1:D1")
    ws1["A1"].alignment = Alignment(horizontal="center", vertical="center")
    ws1.row_dimensions[1].height = 28

    ws1["A2"] = "Team CypherRed261 | PSB Hackathon 2026"
    ws1["A2"].font = Font(bold=False, size=9, color=_XL_WHITE)
    ws1["A2"].fill = PatternFill("solid", fgColor="1A1A2E")
    ws1.merge_cells("A2:D2")
    ws1["A2"].alignment = Alignment(horizontal="center")

    # Metadata fields
    s1_data = [
        ("", ""),
        ("Field", "Value"),
        ("Domain", domain),
        ("Scan ID", str(scan_id)),
        ("Scan Version", version),
        ("Generated At", gen_at[:19].replace("T", " ") + " UTC"),
        ("Generated By", gen_by),
        ("", ""),
        ("Risk Metric", "Value"),
        ("Overall Risk Level", profile.get("risk_level", "N/A")),
        ("PQC Compliance Score", f"{profile.get('pqc_score', 'N/A')} / 100"),
        ("Crypto Agility Score", f"{profile.get('crypto_agility_score', 'N/A')} / 100"),
        ("Cryptographic Mode", profile.get("crypto_mode", "N/A")),
        ("Quantum Risk Horizon", f"{profile.get('quantum_risk_horizon', 'N/A')} years"),
        ("HNDL Risk", "YES" if profile.get("hndl_risk") else "NO"),
        ("Engine Confidence", f"{profile.get('confidence_score', 'N/A')}%"),
        ("Scan Duration (ms)", str(data.get("scan_duration_ms", "N/A"))),
        ("", ""),
        ("Compliance", "Status"),
        ("NIST FIPS 203 (ML-KEM)", "Partial — Migration Recommended" if (profile.get("pqc_score") or 0) < 50 else "Aligned"),
        ("NIST FIPS 204 (ML-DSA)", "Partial — Migration Recommended" if (profile.get("pqc_score") or 0) < 50 else "Aligned"),
        ("NIST FIPS 205 (SLH-DSA)", "Partial — Migration Recommended" if (profile.get("pqc_score") or 0) < 50 else "Aligned"),
        ("RBI Cyber Security Framework", "Non-Compliant" if (profile.get("risk_level") or "").upper() in ("CRITICAL", "HIGH") else "Partial Compliance"),
        ("CERT-IN IT Act", "Non-Compliant" if (profile.get("risk_level") or "").upper() in ("CRITICAL", "HIGH") else "Partial Compliance"),
    ]

    border = _xl_thin_border()
    header_rows = {2, 9, 19}  # 0-indexed offset + 3 for start row
    sub_header_rows = {4, 11, 21}  # actual Excel row numbers for "section headers"

    for i, (label, value) in enumerate(s1_data):
        row = i + 3
        c_label = ws1.cell(row=row, column=1, value=label)
        c_value = ws1.cell(row=row, column=2, value=value)

        is_col_header = label in ("Field", "Risk Metric", "Compliance")
        is_empty = (label == "" and value == "")

        if is_col_header:
            for c in (c_label, c_value):
                c.font = Font(bold=True, size=9, color=_XL_WHITE)
                c.fill = PatternFill("solid", fgColor="333344")
                c.alignment = Alignment(horizontal="center", vertical="center")
                c.border = border
        elif is_empty:
            pass
        else:
            c_label.font = Font(bold=True, size=9)
            c_label.fill = PatternFill("solid", fgColor=_XL_LIGHT)
            c_label.border = border
            c_value.font = Font(size=9)
            c_value.alignment = Alignment(wrap_text=True, vertical="top")
            c_value.border = border

    ws1.column_dimensions["A"].width = 32
    ws1.column_dimensions["B"].width = 45

    # ── Sheet 2: IP Node Details ──────────────────────────────
    ws2 = wb.create_sheet("IP Node Details")
    node_headers = [
        "IP Address", "TLS Version", "Cipher Suite", "Key Exchange",
        "Key Type", "Key Size", "Cert Chain Status", "Scan Status", "Error"
    ]
    node_widths = [18, 12, 35, 28, 16, 14, 20, 14, 30]
    _xl_set_headers(ws2, node_headers, node_widths)

    nodes = data.get("ip_details", [])
    for i, node in enumerate(nodes, start=2):
        tls  = node.get("tls") or {}
        cert = node.get("certificate") or {}
        ok   = node.get("is_successful", True)
        fill = PatternFill("solid", fgColor="F0FDF4") if ok else PatternFill("solid", fgColor="FEF2F2")
        _xl_write_row(ws2, i, [
            node.get("ip_address", ""),
            tls.get("version", ""),
            tls.get("cipher_suite", ""),
            tls.get("key_exchange", ""),
            tls.get("public_key_type", ""),
            str(tls.get("key_size", "")),
            cert.get("chain_status", "UNKNOWN"),
            "SUCCESS" if ok else "FAILED",
            node.get("error_message", ""),
        ], fill=fill)

    # ── Sheet 3: Findings ─────────────────────────────────────
    ws3 = wb.create_sheet("Findings")
    finding_headers = ["Severity", "Type", "Title", "Description"]
    finding_widths  = [14, 18, 38, 65]
    _xl_set_headers(ws3, finding_headers, finding_widths)

    findings = _sort_findings(data.get("findings", []))
    for i, f in enumerate(findings, start=2):
        sev   = (f.get("severity") or "LOW").upper()
        fill  = _SEV_FILL.get(sev, PatternFill("solid", fgColor=_XL_LIGHT))
        row_vals = [
            sev,
            (f.get("type") or "RECOMMENDATION"),
            f.get("title", ""),
            f.get("description", ""),
        ]
        _xl_write_row(ws3, i, row_vals, fill=fill)
        # Severity cell bold + colored
        sev_cell = ws3.cell(row=i, column=1)
        sev_cell.font = Font(bold=True, color=_SEV_FONT_COLOR.get(sev, _XL_DARK), size=9)

    # ── Sheet 4: Recommendations ──────────────────────────────
    ws4 = wb.create_sheet("Recommendations")
    rec_headers = ["Priority", "Title", "Recommendation"]
    rec_widths  = [14, 38, 80]
    _xl_set_headers(ws4, rec_headers, rec_widths)

    recs = [f for f in findings if (f.get("type") or "").upper() == "RECOMMENDATION"]
    for i, f in enumerate(recs, start=2):
        sev  = (f.get("severity") or "LOW").upper()
        fill = _SEV_FILL.get(sev, PatternFill("solid", fgColor=_XL_LIGHT))
        _xl_write_row(ws4, i, [
            sev,
            f.get("title", ""),
            f.get("description", ""),
        ], fill=fill)
        ws4.cell(row=i, column=1).font = Font(bold=True, color=_SEV_FONT_COLOR.get(sev, _XL_DARK), size=9)

    # ── Serialize ─────────────────────────────────────────────
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer.read()
